DROP TABLE IF EXISTS `t1ger_garage`;
CREATE TABLE `t1ger_garage` (
	`identifier` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
	`id` int(11) NOT NULL,
	`vehicles` longtext DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE `t1ger_garage` ADD PRIMARY KEY (`id`);

-- ## OWNED VEHICLES TABLE ## --

-- IF YOU DONT HAVE THESE COLUMNS IN OWNED VEHICLES TABLE, RUN THESE:
ALTER TABLE `owned_vehicles`
ADD IF NOT EXISTS `state` TINYINT(1) NOT NULL DEFAULT 1,
ADD IF NOT EXISTS `type` VARCHAR(20) NOT NULL DEFAULT 'car',
ADD IF NOT EXISTS `fuel` DECIMAL(11, 2) NOT NULL DEFAULT 50,
ADD IF NOT EXISTS `seized` TINYINT(1) NOT NULL DEFAULT 0,
ADD IF NOT EXISTS `garage` VARCHAR(50) NULL DEFAULT NULL;

-- IF U HAVE THE COLUMNS, THEN RUN THESE TO MODIFY THEM
ALTER TABLE `owned_vehicles` MODIFY `state` TINYINT(1) NOT NULL DEFAULT 1;
ALTER TABLE `owned_vehicles` MODIFY `type` VARCHAR(20) NOT NULL DEFAULT 'car';
ALTER TABLE `owned_vehicles` MODIFY `fuel` DECIMAL(11, 2) NOT NULL DEFAULT 50;
ALTER TABLE `owned_vehicles` MODIFY `seized` TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE `owned_vehicles` MODIFY `garage` VARCHAR(50) NULL DEFAULT NULL;
