Lang = {
	-- Notifications:
	['not_near_phonebox']		= 'You are not near a phonebox, else move closer!',
	['already_using_phone_box']	= 'You are already using phone box, please wait.',
	['have_ongoing_job']		= 'You already have an ongoing job, please complete it.',
	['no_jobs_available']		= 'There are no jobs available for this type: %s. Maybe try again for another type?',
	['someone_is_too_close']	= 'Someone is too close, ask him to step back!',
	['encrypted_message']		= '~r~3ncrypt3d m3ss4g3~s~',

	['hacking_setup_job']		= 'HACKING SETUP JOB',
	['hacking_job_start']		= 'Find the encrypted device!\n\nGPS Location sent!\nStreet: %s',
	['device_being_decrypted']	= 'Device is already being decrypted..',
	['decryption_started']		= 'Decryption software initialized, wait till it\'s complete and grab the device back again.',
	['decryption_failed']		= 'Decryption software failed to initialize, device got corrupted.',
	['find_spot_to_decrypt']	= 'Figure out the correct spot to decrypt the encrypted device.',
	['hack_police_alert']		= '^0[INTRUDER] - Alarm has been triggered at ^3%s^0',
	['got_decrypted_device']	= 'You received the ~r~decrypted device~s~, now yeet before the heat arrives!',
	['device_already_collect']	= 'Someone was quicker than you to collect the ~r~decrypted device~s~.',

	['drills_setup_job']		= 'DRILLS SETUP JOB',
	['drills_job_start']		= 'Go to the ~y~location~s~ on %s, and find the drill crates!\n\nGPS Location sent!',
	['drills_being_searched']	= 'Someone is already searching the drills crate.',
	['got_necessary_drills']	= 'You got the necessary drills, now escape from the site!',
	['drills_alrdy_searched']	= 'The crate has already been searched.',
	['you_found_a_drill']		= 'You found a drill in the crate.',
	['you_found_nothing']		= 'You found nothing in the crate.',
	
	['thermite_setup_job']		= 'THERMITE SETUP JOB',
	['thermite_job_start']		= 'Ambush the ~r~convoy~s~ before it reaches it\'s destination.\n\nConvoy GPS is pinged!',
	['kill_guard_b4_search']	= 'Take out the security guards before searching!',
	['convoy_being_searched']	= 'Someone is already searching the convoy.',
	['found_thermal_charges']	= 'You found %sx ~r~thermal charges~s~ in the trunk, now get outta here!',
	['convoy_alrdy_searched']	= 'The convoy has already been searched.',
	
	['explosives_setup_job']	= 'EXPLOSIVES SETUP JOB',
	['explosives_job_start']	= 'Find the case containing explosive charges at the ~y~location~s~\n\nYou may need some diving gear!',
	['maybe_bring_diving_gear']	= 'You might need a set of diving gear to hold the breath',
	['case_already_collected']	= 'Someone already collected case quicker than you.',
	['return_to_the_shore']		= 'Return to the ~y~shore~s~ and unlock the case.',
	['unlock_the_case']			= 'Unlock the case..',
	['case_being_unlocked']		= 'Someone is already unlocking the case.',
	['found_explosive_charge']	= 'You unlocked the case and received ~r~explosive charges~s~. Now yeet!',
	['failed_to_unlock']		= 'You failed to unlock the case, keep trying until you nail it!',
	
	['keycard_setup_job']		= 'KEYCARD SETUP JOB',
	['keycard_job_start']		= 'Find the bankman with the ~b~master-truck-keys~s~.\n\nGPS location: %s',
	['search_bankman']			= 'Go to the ~r~ped~s~ and search for the ~b~master-truck-keys~s~',
	['bankman_being_searched']	= 'Someone is already searching the bankman.',
	['trucks_tracked_down']		= 'I have tracked down some parked ~b~bank trucks~s~\n\nGPS Locations sent!',
	['truck_being_searched']	= 'Someone is already searching the bank truck.',
	['truck_already_searched']	= 'The bank truck has already been searched.',
	['found_keycard_in_truck']	= 'You found a maze bank keycard in the bank truck.',
	['found_nothing_in_truck']	= 'You found nothing, try the others trucks.',
	['found_keycards']			= 'You got the necessary keycards, now yeet!',

	-- Draw Texts:
	['draw_decrypt_device']		= '~r~[E]~s~ Decrypt Device',
	['draw_collect_device']		= '~r~[E]~s~ Collect Device',
	['draw_search_c_trunk']		= '~r~[E]~s~ Search Convoy Trunk',
	['draw_place_case']			= '~r~[E]~s~ Place Case',
	['draw_unlock_case']		= '~r~[E]~s~ Unlock Case',
	['draw_search_ped']			= '~r~[E]~s~ Search Ped',
	['draw_unlock_b_truck']		= '~r~[E]~s~ Unlock Bank Truck',
	
	-- Progress Bars:
	['pb_request_job']			= 'REQUEST SETUP JOB',
	['pb_decrypting']			= 'INITIALIZING DECRYPTING SOFTWARE',
	['pb_searching_crate']		= 'SEARCHING CRATE',
	['pb_searching_convoy']		= 'SEARCHING CONVOY TRUNK',
	['pb_unlocking']			= 'UNLOCKING CASE',
	['pb_searching_ped']		= 'SEARCHING BANK MAN',
	['pb_searching_truck']		= 'SEARCHING BANK TRUCK',
} 
