-------------------------------------
------- Created by T1GER#9080 -------
------------------------------------- 

Lang = {
  -- Notifications:
	['invalid_string']          = 'Invalid String',
	['not_enough_money']        = 'You do not have enough money.',
	['company_purchased']       = 'You purchased a ~b~delivery company~s~ and paid ~g~$%s~s~',
	['company_renamed']         = '~g~Company has been renamed.~s~',
	['company_sold']          	= 'You sold your ~b~delivery company~s~ and received ~g~$%s~s~',
	['get_account_balance']  	  = 'Current Account Balance: ~g~$%s~s~.',
  ['certificate_acquired']    = 'Your company has now acquired a certificate',
  ['job_needs_certificate']   = 'The job requires a certificate',
  ['job_level_mismatch']      = 'Your current level does not match the job requirements',
  ['no_available_orders']     = 'No available orders to claim.',
  ['deposit_veh_paid']        = 'You paid ~g~$%s~s~ in deposit for the vehicle.',
  ['not_enough_to_deposit']   = 'You do not have enough money to pay the deposit.',
  ['forklift_mismatch']       = 'This is not the correct forklift?',
  ['not_inside_forklift']     = 'You need to bring the forklift',
  ['trailer_filled_up']       = 'You filled up the ~b~trailer~s~. Attach the trailer to truck and start the ~y~deliveries~s~.',
  ['park_fork_in_trailer']    = 'Park the ~y~forklift~s~ inside the ~b~trailer~s~ again.',
  ['place_pallet_on_ground']  = 'Park the ~r~pallet~s~ on the ground!',
  ['set_delivery_route']      = 'Continue the ~b~delivery~s~ to the next ~y~destination~s~.',
  ['delivery_pallets_done']   = 'You delivered all pallets. Return to the office retrieve the ~g~paycheck~s~.',
  ['job_veh_mismatch']        = 'This is not your job vehicle?',
  ['sit_in_job_veh']          = 'Please bring your job vehicle!',
  ['pallet_damaged_transit']  = 'This pallet was damaged in transit, no payment for this delivery',
  ['paycheck_add_amount']     = '~g~+$%s~s~ [added to paycheck]',
  ['job_veh_spawned']         = 'Your vehicle has arrived and you received a pair of keys.',
  ['job_trailer_spawned']     = 'Trailer is ready to be loaded.',
  ['delivery_complete']       = 'You delivered all parcels. Return the ~b~vehicle~s~ and retrieve the ~g~paycheck~s~.',
  ['parcel_not_ind_hand']     = 'Take a ~y~parcel~s~ from the vehicle.',
  ['vehicle_filled_up']       = 'You filled up the ~b~vehicle~s~. Get in and start the ~y~deliveries~s~.',
  ['parcel_damaged_transit']  = 'This parcel was damaged in transit, no payment for this delivery',
  ['deposit_not_returned']    = 'Deposit ~r~not returned~s~, vehicle is ~r~damaged~s~ too much.',
  ['deposit_returned']        = '~g~+$%s~s~ [vehicle deposit returned]',
  ['paycheck_received']       = '~g~+$%s~s~ [paycheck added in society account]',
  
	-- Draw Texts:
	['draw_company_menu']       = '~r~[E]~s~ Company Menu',
	['draw_company_no_access']  = 'NO ACCESS',
	['draw_buy_company']       	= '~r~[E]~s~ Buy Company [~g~$%s~s~]',
	['draw_company_own_one']    = 'ONLY OWN ONE COMPANY',
  ['draw_fill_up_trailer']    = '~r~[E]~s~ Fill Up Trailer',
  ['draw_park_forklift']      = '~r~[G]~s~ Park Forklift',
  ['draw_take_forklift']      = '~r~[G]~s~ Take Out Forklift',
  ['draw_deliver_pallet']     = '~r~[E]~s~ Deliver Pallet',
  ['draw_return_vehicle']     = '~r~[E]~s~ Return Vehicle | Get Paycheck',
  ['draw_pallet_in_trailer']  = '~r~[E]~s~ Put Pallet in Trailer',
  ['draw_fill_up_vehicle']    = '~r~[E]~s~ Fill Up Vehicle',
  ['draw_take_parcel']        = '~r~[E]~s~ Take Parcel from Vehicle',
  ['draw_deliver_parcel']     = '~r~[G]~s~ Deliver Parcel',
  ['draw_pick_up_parcel']     = '~r~[E]~w~ Pick Up Parcel',
  ['draw_parcel_in_veh']      = '~r~[E]~s~ Put Parcel in Vehicle',
  
	-- Draw Mission Texts:
  ['forklift_into_trailer']   = 'Drive the ~y~forklift~s~ into the ~b~Trailer~s~',
  ['park_instrunctions']      = 'Park the ~y~rear end~s~ of the ~b~Trailer~s~ at the ~r~Marker~s~',
  ['pick_up_the_pallet']      = 'Pick up the ~r~Pallet~s~',
  ['drop_off_the_pallet']     = 'Deliver the Pallet',
  ['pick_up_pallet']          = 'Pick up a ~r~Pallet~s~',
  ['load_into_trailer']       = 'Load the ~r~Pallet~s~ into the ~b~Trailer~s~',
}