-------------------------------------
------- Created by T1GER#9080 -------
------------------------------------- 

Lang = {
  -- CHAT MESSAGES:
  ['dispatch_name']           = '^5 Dispatch: ',
  ['police_notification1']    = '^0^*Armed^r Grand Theft Auto at ^3%s^0 | ^6^*Make: ^0^*%s | ^6Plate: ^0^*%s | ^6Colors: ^0^*%s ^6on ^0^*%s',
  ['police_notification2']    = '^0Grand Theft Auto at ^3%s^0 | ^6^*Make: ^0^*%s | ^6Plate: ^0^*%s | ^6Colors: ^0^*%s ^6on ^0^*%s',
  ['alarm_central']           = '^5 Alarm Central: ',
  ['vehicle_alarm_triggered'] = '^0Your vehicle [%s] alarm has been triggered at ^3%s^0',

  -- MENU STRINGS:
  ['button_yes']           	  = 'Yes',
  ['button_no']           	  = 'No',
  ['shop_main_title']         = 'Select a Vehicle',
  ['reg_key_title']           = 'Register Key Price: $%s',
  ['reg_alarm_title']         = 'Aquire Alarm Price: $%s',
  ['your_current_keys']       = 'Your Current Keys',
  ['keys_actions_title']      = 'Keys Action [%s]',
  ['give_key_menu']           = 'Give Keys',
  ['remove_key_menu']         = 'Remove Keys',
  ['delete_key_menu']         = 'Delete Keys',
  ['car_interaction_title']   = 'Car Interaction Menu',
  ['keys_mangement_label']    = 'Keys Mangement',
  ['veh_windows_label']       = 'Windows Options',
  ['veh_door_label']          = 'Doors Options',
  ['veh_engine_label']        = 'Engine On/Off',
  ['veh_neon_label']          = 'Neon On/Off',
  ['insurance_label']         = 'Insured Vehicles',
  ['windows_menu_title']      = 'Windows Up/Down',
  ['window_front_r']       		= 'Front Window (R)',
  ['window_front_l']       		= 'Front Window (L)',
  ['window_rear_r']       		= 'Rear Window (R)',
  ['window_rear_l']       		= 'Rear Window (L)',
  ['doors_menu_title']        = 'Open/Close Door',
  ['door_hood']      			    = 'Hood',
  ['door_trunk']       			  = 'Trunk',
  ['door_front_l']            = 'Front Door (L)',
  ['door_front_r']            = 'Front Door (R)',
  ['door_rear_l']             = 'Rear Door (L)',
  ['door_rear_r']             = 'Rear Door (R)',

  -- NOTIFICATIONS:
  ['check_f8_console']        = '~r~CHECK F8 CONSOLE!!!~s~',
  ['not_enough_money']        = 'You do not have enough money.',
  ['no_players_nearby']       = 'No players nearby.',
  ['no_veh_nearby']           = 'No vehicles nearby.',
  ['no_owned_vehicles']       = 'You do not have any owned vehicles.',
  ['engine_not_running']      = 'Engine must be running!',
  ['must_be_inside_veh']      = 'You must be inside a vehicle!',
  ['must_be_driver_of_veh']   = 'You must be in the driver seat of the vehicle!',
  ['veh_must_be_unlocked']    = 'Vehicle must be unlocked.',
  ['no_veh_in_direction']     = 'No vehicle(s) in that direction.',
  ['vehicle_locked']          = 'You ~r~locked~s~ your vehicle',
  ['vehicle_unlocked']        = 'You ~g~unlocked~s~ your vehicle',
  ['has_key_false']         	= 'You don\'t have keys for that car',
  ['all_veh_has_keys']        = 'You have registered keys to all your vehicles.',
  ['key_reg_accepted']        = 'You registered a new pair of keys for the selected vehicle.',
  ['all_veh_have_alarm']      = 'You have alarm for all your vehicles.',
  ['alarm_aquired']           = 'You aquired an alarm for the selected vehicle.',
  ['no_registerd_keys']       = 'You have no registered keys to display',
  ['keys_received1']          = 'You ~g~received~s~ a pair of keys for a vehicle ~b~[%s]~s~.',
  ['keys_received2']          = 'You ~g~received~s~ a pair of keys for a vehicle ~b~[%s]~s~ from %s.',
  ['u_gave_keys']             = 'You gave keys [%s] to %s',
  ['u_removed_a_key']         = 'You removed keys [%s] from %s',
  ['u_had_a_key_removed']     = 'Your keys [%s] has been removed by %s',
  ['target_has_no_key_copy']  = '%s does not have a copy of that key...',
  ['couldnt_find_keys']       = 'Could not find keys for vehicle /w plate: %s',
  ['keys_deleted']            = 'Keys for %s [%s] have been deleted.',
  ['engine_toggled_on']       = 'You ~g~turned on~s~ vehicle engine',
  ['engine_toggled_off']      = 'You ~r~turned off~s~ vehicle engine',
  ['npc_ran_away']      		  = 'The NPC ran away with the keys',
  ['already_lockpicking']     = 'You are already lockpicking a vehicle!',
  ['move_closer_to_lockpick'] = 'Move closer to lockpick vehicle.',
  ['first_check_if_locked']   = 'Please check whether the vehicles is locked or not...',
  ['deny_lockpick_unlocked']  = 'You cannot lockpick a vehicle that\'s not locked..',
  ['veh_lockpicked_success']  = 'You ~y~lockpicked~s~ the vehicle.',
  ['veh_lockpicked_fail']     = 'You ~r~failed~s~ to ~y~lockpicked~s~ the vehicle.',
  ['deny_hotwire']            = 'Vehicle does not require to be hotwired.',
  ['hotwire_the_vehicle']     = 'Hotwire the vehicle to turn the engine on.',
  ['already_hotwiring']       = 'You are already hotwiring a vehicle!',
  ['veh_hotwire_success']     = 'You ~y~hotwired~s~ the vehicle.',
  ['veh_hotwire_fail']        = 'You ~r~failed~s~ to ~y~hotwire~s~ the vehicle.',
  ['already_searching']       = 'You are already searching a vehicle!',
  ['stop_the_vehicle']        = 'Please stop the vehicle first!',
  ['cannot_search_car']       = 'This car is empty, dont even bother!',
  ['cash_found_x']      		  = 'You found ~g~$%s~s~ in cash.',
  ['item_found_x']      			= 'You found ~b~%sx~s~ ~y~%s~s~.',

  

  -- DRAW TEXTS:
  ['draw_locksmith']          = '~r~[E]~s~ Lock Smith',
  ['draw_alarmshop']          = '~r~[E]~s~ Alarm Shop',

  -- PROGRESSBARS:
  ['progbar_talking']         = 'TALKING /W NPC',
  ['progbar_searching']       = 'SEARCHING',
  ['progbar_hotwiring']       = 'HOTWIRING',
  ['progbar_lockpicking']     = 'LOCKPICKING',
  
  -- BLIPS:
  ['blip_locksmith']          = 'Locksmith',
  ['blip_alarmshop']          = 'Alarm Shop',
}
